Fix chain of implied permissions
mikecirioli/jenkins pull request #17
Opened 2019-11-04 11:01 UTC by EstherAF

The GeneralRead permission wasn't implied by CONFIGURE_JENKINS. Now it is:
`Administer -> Configure -> GeneralRead -> Read`

[CTR-803](https://cloudbees.atlassian.net/browse/CTR-803)

@aHenryJard @mikecirioli

2019-11-04 11:19 UTC, amuniz reviewed
There is a lot of unrelated changes here. Did you branch from the wrong commit?

2019-11-04 14:25 UTC, EstherAF commented
> There is a lot of unrelated changes here. Did you branch from the wrong commit?

I branched from the jenkinsci/jenkins master branch, but mike's is not updated, fixing this...
Thanks!

2019-11-04 14:34 UTC, EstherAF commented on core/src/main/java/hudson/security/Permission.java
> +    public static final Permission READ = new Permission(GROUP,"GenericRead",null,CONFIGURE_JENKINS);
Originally (before FGP) this READ permission was implied directly by ADMINISTER.

Also, the existent CONFIGURE allows configuring items (like agents, jobs, etc). We don't want CONFIGURE_JENKINS to allow that, so can't imply it.

Couldn't find a better way of making CONFIGURE_JENKINS imply Jenkins.READ and Permission.READ.

2019-11-07 07:47 UTC, aHenryJard requested changes
We should wait until we finished design for this PR, as it's impacting the permission model.

2019-11-08 14:58 UTC, EstherAF commented
This PR has no sense after https://github.com/mikecirioli/jenkins/pull/15. I'm closing it.

2019-11-08 14:58 UTC, closed without merging